name: 'build'

on:
  push:
    branches:
      - master
      - ci-dev

env:
  WINSDK_VERSION: 22621

jobs:
  build-straycat:
    permissions:
      contents: write

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        id: winsdk
        with:
          sdk-version: ${{ env.WINSDK_VERSION }}
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Copy CI build script
        run: (Get-Content .\build.rs) -replace '26100', '${{ env.WINSDK_VERSION }}' | Set-Content .\build.rs
      - name: Build Straycat
        run: cargo build --release
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: straycat-build
          path: target/release/straycat-rs.exe
  
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    needs: build-straycat
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: straycat-build

      - name: Get version from Cargo.toml
        uses: thebongy/version-check@v2
        with:
          file: Cargo.toml
          tagFormat: v${version}
        id: getversion

      - name: Get checksums for build
        id: checksums
        run: |
          echo SHA256="$(shasum straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo SHA512="$(shasum -a 512 straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo MD5="$(md5sum straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: v${{ steps.getversion.outputs.releaseVersion }}

      - name: Create tag
        if: steps.check-tag.outputs.exists == 'false' 
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.getversion.outputs.releaseVersion }}',
              sha: context.sha
            })

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          make_latest: true
          files: "./*.exe"
          name: 'straycat-rs ${{ steps.getversion.outputs.releaseVersion }}'
          tag_name: 'v${{ steps.getversion.outputs.releaseVersion }}'
          body: |
            `A stable build of straycat-rs.
            ### Changes

            ### Fixed

            ### Hashes
            | Hash function | Hash |
            | --- | --- |
            | SHA256 | ${{ steps.checksums.outputs.SHA256 }} |
            | SHA512 | ${{ steps.checksums.outputs.SHA512 }} |
            | MD5 | ${{ steps.checksums.outputs.MD5 }} |
            `
          generate_release_notes: true