name: 'build'

on:
  push:
    branches:
      - release
      - release-test

env:
  WINSDK_VERSION: 22621

jobs:
  build-straycat:
    permissions:
      contents: write

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        id: winsdk
        with:
          sdk-version: ${{ env.WINSDK_VERSION }}
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Copy CI build script
        run: (Get-Content .\build.rs) -replace '26100', '${{ env.WINSDK_VERSION }}' | Set-Content .\build.rs
        # run: Copy-Item -Path .\.github\build.rs -Destination .\build.rs -force
      - name: Build Straycat
        run: cargo build --release
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-straycat

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-get plugin
        run: cargo install cargo-get
      - name: Get version from Cargo.toml
        id: getversion
        run: |
          echo "Building Straycat version: $(cargo get package.version)"
          echo ::set-output name=version::$(cargo get package.version)
        # run: echo "PACKAGE_VERSION=$(cargo get package.version)" >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/straycat-v${{ steps.getversion.outputs.version }}',
              sha: context.sha
            })

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: straycat-v${{ steps.getversion.outputs.version }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          commit: release-test
          artifacts: .\target\release\straycat-rs.exe
          name: 'Straycat version ${{ steps.getversion.outputs.version }}'
          tag: 'straycat-v${{ steps.getversion.outputs.version }}'
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for straycat-v${{ steps.getversion.outputs.version }} [skip ci]'
          file_pattern: CHANGELOG.md