name: 'build'

on:
  push:
    branches:
      - master
      - ci-dev

env:
  WINSDK_VERSION: 22621

jobs:
  build-straycat-win:
    permissions:
      contents: write

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        id: winsdk
        with:
          sdk-version: ${{ env.WINSDK_VERSION }}
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Copy CI build script
        run: (Get-Content .\build.rs) -replace '26100', '${{ env.WINSDK_VERSION }}' | Set-Content .\build.rs
      - name: Build Straycat
        run: cargo build --release
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win
          path: target/release/straycat-rs.exe

  build-straycat-mac-silicon:
    permissions:
      contents: write

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1.0.6
        with:
         toolchain: stable
      - name: Build Straycat
        run: cargo build --release
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-silicon
          path: target/release/straycat-rs

  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    needs: [build-straycat-win, build-straycat-mac-silicon]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Get version from Cargo.toml
        uses: thebongy/version-check@v2
        with:
          file: Cargo.toml
          tagFormat: v${version}
        id: getversion

      - name: Get checksums for build
        id: checksums
        run: |
          echo WIN_SHA1="$(shasum -a 1 win/straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo WIN_SHA256="$(shasum -a 256 win/straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo WIN_SHA384="$(shasum -a 384 win/straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo WIN_MD5="$(md5sum win/straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo MAC_SHA1="$(shasum -a 1 mac-silicon/straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo MAC_SHA256="$(shasum -a 256 mac-silicon/straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo MAC_SHA384="$(shasum -a 384 mac-silicon/straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          echo MAC_MD5="$(md5sum mac-silicon/straycat-rs.exe | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: ${{ steps.getversion.outputs.releaseVersion }}

      - name: Create tag
        if: steps.check-tag.outputs.exists == 'false' 
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.getversion.outputs.releaseVersion }}',
              sha: context.sha
            })

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          make_latest: true
          files: |
            win/straycat-rs.exe
            mac-silicon/straycat-rs
          name: 'straycat-rs ${{ steps.getversion.outputs.rawVersion }}'
          tag_name: '${{ steps.getversion.outputs.releaseVersion }}'
          body: |
            # straycat-rs ${{ steps.getversion.outputs.rawVersion }}

            A stable build of straycat-rs.

            ## [${{ steps.getversion.outputs.rawVersion }}] - xxxx-xx-xx

            ### Added

            ### Changed

            ### Fixed

            ### Hashes
            #### Windows
            | Hash function | Hash |
            | --- | --- |
            | MD5 | `${{ steps.checksums.outputs.WIN_MD5 }}` |
            | SHA1 | `${{ steps.checksums.outputs.WIN_SHA1 }}` |
            | SHA256 | `${{ steps.checksums.outputs.WIN_SHA256 }}` |
            | SHA384 | `${{ steps.checksums.outputs.WIN_SHA384 }}` |

            #### MacOS (Silicon)
            | Hash function | Hash |
            | --- | --- |
            | MD5 | `${{ steps.checksums.outputs.MAC_MD5 }}` |
            | SHA1 | `${{ steps.checksums.outputs.MAC_SHA1 }}` |
            | SHA256 | `${{ steps.checksums.outputs.MAC_SHA256 }}` |
            | SHA384 | `${{ steps.checksums.outputs.MAC_SHA384 }}` |

            **Full Changelog**: https://github.com/UtaUtaUtau/straycat-rs/blob/main/CHANGELOG.md
          generate_release_notes: true
